In [4]:
!python q1_softmax.py

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!

Running your tests...
Traceback (most recent call last):
  File "q1_softmax.py", line 91, in <module>
    test_softmax()
  File "q1_softmax.py", line 85, in test_softmax
    raise NotImplementedError
NotImplementedError


In [12]:
import numpy as np 
np.max([[1,2,3],[4,5,6]], axis=1)

array([3, 6])

In [7]:
!python q2_sigmoid.py

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!

Running your tests...
Traceback (most recent call last):
  File "q2_sigmoid.py", line 81, in <module>
    test_sigmoid()
  File "q2_sigmoid.py", line 75, in test_sigmoid
    raise NotImplementedError
NotImplementedError


In [19]:
!python q2_gradcheck.py

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

Running your sanity checks...
Traceback (most recent call last):
  File "q2_gradcheck.py", line 87, in <module>
    your_sanity_checks()
  File "q2_gradcheck.py", line 81, in your_sanity_checks
    raise NotImplementedError
NotImplementedError


In [22]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x[np.arange(2),[1,2]]

array([2, 6])

In [27]:
!python q2_neural.py

Running sanity check...
Gradient check passed!
Running your sanity checks...
Traceback (most recent call last):
  File "q2_neural.py", line 117, in <module>
    your_sanity_checks()
  File "q2_neural.py", line 111, in your_sanity_checks
    raise NotImplementedError
NotImplementedError


In [42]:
- np.log(0.1)

2.3025850929940455

In [72]:
!python q3_word2vec.py

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.166109001533981, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947339, -1.36873189,  2.45158957],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.41045956,  0.18834851,  1.43272264],
       [ 0.38202831, -0.17530219, -1.33348241],
       [ 0.07009355, -0.03216399, -0.24466386],
       [ 0.09472154, -0.04346509, -0.33062865],
       [-0.13638384,  0.06258276,  0.47605228]]))
(13.959405258751875, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-4.12113804, -1.67347865, -1.5049951 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.  

In [6]:
import numpy as np 
print -3./7 * np.log(3./7)

0.363127654452


In [24]:
from q2_sigmoid import sigmoid, sigmoid_grad
print sigmoid(1)
print sigmoid(-1)
print sigmoid(1) + sigmoid(-1)

0.73105857863
0.26894142137
1.0


In [3]:
!python q3_sgd.py

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.41483678608e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.52445103582e-09

Running your sanity checks...
Traceback (most recent call last):
  File "q3_sgd.py", line 143, in <module>
    your_sanity_checks()
  File "q3_sgd.py", line 137, in your_sanity_checks
    raise NotImplementedError
NotImplementedError
